version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ./env/postgres.env
    environment:
      TZ: "Europe/Paris" #maybe not useful
    restart: unless-stopped 
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
 
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./env/pgadmin.env
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    networks:
      - backend
    depends_on:
      - postgres

  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend
    volumes:
      - ./backend:/app
    env_file:
      - ./env/back.env
    restart: unless-stopped
    depends_on:
      - postgres
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
    - 8080:8080
    networks:
      - backend
    volumes:
     - ./frontend:/app
    env_file:
      - ./env/front.env
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  data:

networks:
  backend: